### ISSUE TITLE
on the CentOS7.7 systemctl reload auditd doesnot work

### ISSUE THREAD

**Issue by arm2arm** [pschiffe/ipa-log-config#16]
The command gives an error.
./ipa_log_config.py --revert
Setting SSSD debug level to 1
Condrestarting SSSD
Disabling audisp syslog plugin
Reloading auditd
Failed to reload auditd.service: Job type reload is not applicable for unit auditd.service.
See system logs and 'systemctl status auditd.service' for details.
Failed to execute external command: Failed to reload auditd
to solve simply change the line:
line 117 to 
if call(['/usr/sbin/service','auditd', 'reload']) != 0:

**Comment by pschiffe** [comment]
Thank you for the report.
